### ISSUE TITLE
UniVerse issue_수강 내역 조회

### ISSUE THREAD

**Issue by moomint8** [beyond-sw-camp/be04-1st-CLOUDY-UniVerse#13]
### 01. 목적

> 학생은 자신이 수강 완료한 강의에 대한 정보를 조회할 수 있다. 
> - 학번과 수강 과목을 입력 받아 일치하는 수강 과목 테이블을 불러온다.

> 학생은 현재 자신이 수강 중인 강의에 대한 정보를 조회할 수 있다.

### 02. 조회 데이터(JOIN사용)
1. 학생(course_lecture_tb.student_id=student_tb.id
            course_lecture_tb.lecture_id=lecture_tb .id)
- 학번
- 이름
- 강의명
- 성적 알파벳
- 성적 숫자
- 이수구분
- 강의평가여부
- 강의평가내용
- 이수연도

2. 학생(student_tb.id = course_lecture_tb.student_id
             course_lecture_tb.id=lecture_tb.id)
- 학번
- 이름
- 강의명
- 이수구분

**Comment by daersh** [comment]
자신의 수강 과목 조회 확인했습니다.
