### ISSUE TITLE
UniVerse issue_교수 조회

### ISSUE THREAD

**Issue by moomint8** [beyond-sw-camp/be04-1st-CLOUDY-UniVerse#18]
### 01. 목적

> "학생은 교수의 정보를 조회할 수 있다. 
교수의 이름, 사진, 이메일,연락처,학과,위치하는 관, 관 위치를 불러온다."

### 02. 조회 데이터(JOIN사용)
1. 교수(curriculum_tb.department_id = department_tb.id)
- 학과 명
- 교수 이름

**Comment by daersh** [comment]
작동 확인했습니다.
