### ISSUE TITLE
UniVerse issue_기자재 대여

### ISSUE THREAD

**Issue by Leegiyeon** [beyond-sw-camp/be04-1st-CLOUDY-UniVerse#20]
### 1. 목적

> 01. 학생과 교수가 대여 가능한 기자재를 조회할 수 있다.

> 02. 학생과 교수가 자신이 대여한 기자재를 조회할 수 있습니다. 

### 2.조회 데이터(JOIN사용)

01. 대여 가능한 기자재 조회 

학생
(student_tb.id = rent_equipment_tb.student_id)
(rent_equipment_tb..equipment_id = equipment.id)
- 기자재 명
- 설명
- 잔여 수량

교수
(professor_tb.id = rent_equipment_tb.student_id)
(rent_equipment_tb..equipment_id = equipment.id)
- 기자재 명
- 설명
- 잔여 수량

02. 대여한 기자재 조회

학생(student_tb.id = rent_equipment_tb.student_id)
- 기자재 명
- 대여 기간
- 대여 수량

교수(professor_tb.id = rent_equipment_tb.student_id)
- 기자재 명
- 대여 기간
- 대여 수량

**Comment by noctesilente** [comment]
확인 완료했습니다.

1. 대여 가능한 기자재 조회
SELECT b.name as '카테고리',a.id as '기자재번호', a.name as '기자재 이름', a.explain as '설명', a.total_cnt as '총 수량', a.residual_cnt as '잔여수량', a.equipment_img as '사진', c.name as '위치'
  FROM EQUIPMENT_TB a
  JOIN equipment_category_tb b on a.category_code_id=b.id
  JOIN structure_tb c on a.structure_id = c.id
 WHERE a.residual_cnt != 0;

2-1. 학생이 자신이 대여한 기자재 조회
SELECT c.id as '대여자id',c.name as '대여자' ,b.name as '기자재',a.rental_cnt as '대여수량',a.rental_dt as '대여일',a.due_dt as '반납일'
  FROM rent_equipment_tb a 
  JOIN equipment_tb b on a.equipment_id = b.id
  JOIN student_tb c on a.student_id=c.id
 WHERE c.id= 20230047;

2-2. 교수가 자신이 대여한 기자재 조회
SELECT c.id as '대여자id',c.name as '대여자' ,b.name as '기자재',a.rental_cnt as '대여수량',a.rental_dt as '대여일',a.due_dt as '반납일'
  FROM rent_equipment_tb a 
  JOIN equipment_tb b on a.equipment_id = b.id
  JOIN professor_tb c on a.professor_id=c.id
 WHERE c.id= 20
